# Generated by Django 5.2.5 on 2025-08-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookCollector',
            fields=[
                ('cook', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cook_full', models.CharField(max_length=100)),
                ('cook_app', models.CharField(max_length=100)),
                ('recipe_box_image', models.URLField()),
                ('cook_head_shot', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('cook', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category_cards/')),
                ('cook', models.ForeignKey(default='Cookie', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='recipes.cookcollector')),
            ],
        ),
    ]
