# Generated by Django 5.2.5 on 2025-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookcollector',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
