# Generated by Django 5.2.4 on 2025-08-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookCollector',
            fields=[
                ('cook', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('cook_full', models.CharField(max_length=128)),
                ('cook_app', models.CharField(max_length=64)),
                ('cook_head_shot', models.CharField(max_length=256)),
                ('recipe_box_image', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
